"use client";
import "./globals.css";
import { GetData } from "@/Components/Getdata";
import MyContext from "@/Helper/Context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MyContext> {children}</MyContext>
      </body>
    </html>
  );
}
